# Generated by Django 5.0.1 on 2024-01-24 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_projectmodel_projectlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodel",
            name="dateCreated",
            field=models.DateField(
                default=datetime.datetime(2024, 1, 24, 5, 34, 22, 246220)
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="dateFinished",
            field=models.DateField(
                default=datetime.datetime(2024, 1, 24, 5, 34, 22, 246237)
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="description",
            field=models.TextField(default="Project Description Unavailable"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="frameworks",
            field=models.TextField(
                default="Angular,Spring Boot,PyTorch,Django,JavaFx,matplotlib,numpy,albumentations,Open CV"
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="githubUrl",
            field=models.URLField(default="https://github.com/LynnHaDo"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="imageUrl",
            field=models.TextField(default="../../../assets/logo.png"),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="languages",
            field=models.TextField(
                default="HTML,CSS,TypeScript,JavaScript,Java,Python,R"
            ),
        ),
    ]
