# Generated by Django 5.0.1 on 2024-01-28 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_projectmodel_datecreated_projectmodel_datefinished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="dateCreated",
            field=models.DateField(
                default=datetime.datetime(2024, 1, 28, 21, 16, 45, 747302)
            ),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="dateFinished",
            field=models.DateField(
                default=datetime.datetime(2024, 1, 28, 21, 16, 45, 747316)
            ),
        ),
    ]
